name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 50

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 'stable'

    - name: Run lint
      run: make lint

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@490e2450418f2d55f0e912d548cbae3b1fbc8e83
      with:
        version: 'latest'

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 50

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 'stable'

    - name: Run tests
      run: |
        go test -v -mod=vendor ./...
        ./integrationtest.sh
